# Cloudflare Tunnel Stack
# Secure external access via Cloudflare Zero Trust

services:
  # =============================================================================
  # CLOUDFLARE TUNNEL - Secure External Access
  # =============================================================================
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - proxy_network
    depends_on:
      - traefik
    labels:
      - "traefik.enable=false"

# =============================================================================
# NETWORKS
# =============================================================================
networks:
  proxy_network:
    external: true

