# database.yml
version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database_network
    secrets:
      - postgres_password

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - database_network

  mariadb:
    container_name: mariadb
    image: lscr.io/linuxserver/mariadb:latest
    restart: unless-stopped
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      MYSQL_DATABASE: maria_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
    volumes:
      - mariadb_config:/config
    networks:
      - database_network
    secrets:
      - mysql_root_password
      - mysql_user_password

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_DEFAULT_EMAIL_FILE: /run/secrets/pgadmin_email
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - database_network
    secrets:
      - pgadmin_email
      - pgadmin_password

networks:
  database_network:
    external: true

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_user_password:
    file: ./secrets/mysql_user_password.txt
  pgadmin_email:
    file: ./secrets/pgadmin_email.txt
  pgadmin_password:
    file: ./secrets/pgadmin_password.txt
