
# security.yml
version: '3.8'

services:
  vaultwarden:
    <<: *default-app-config # Extend common settings
    container_name: vaultwarden
    image: ghcr.io/dani-garcia/vaultwarden:latest
    restart: always
    ports:
      - "${VAULTWARDEN_PORT}:80"
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false # Set to true initially, then false
    volumes:
      - vaultwarden_data:/data # Changed to named volume
    networks:
      - security_network

  wazuh-manager:
    container_name: wazuh-manager
    image: wazuh/wazuh-manager:latest # Pin a specific version, e.g., 4.7.2
    hostname: wazuh-manager
    restart: always
    ports:
      - "${WAZUH_MANAGER_API_PORT}:55000/tcp"
      - "1514:1514/udp"
      - "1515:1515/tcp"
    environment:
      WAZUH_PATH: "/var/ossec"
      DISABLE_SSL: "true" # Keep for testing, but secure in production!
    volumes:
      - wazuh_manager_data:/var/ossec # Changed to named volume
      - wazuh_manager_certs:/usr/share/filebeat/certs # Changed to named volume
    networks:
      - wazuh_network

  wazuh-indexer:
    container_name: wazuh-indexer
    image: opensearchproject/opensearch:2.11.1
    hostname: wazuh-indexer
    restart: always
    environment:
      - node.name=wazuh-indexer
      - cluster.name=wazuh-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - DISABLE_SECURITY_PLUGIN=true # Keep for testing, secure in production!
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - wazuh_indexer_data:/usr/share/opensearch/data # Changed to named volume
    ports:
      - "${WAZUH_INDEXER_PORT}:9200"
    networks:
      - wazuh_network

  wazuh-dashboard:
    container_name: wazuh-dashboard
    image: wazuh/wazuh-dashboard:4.7.2
    hostname: wazuh-dashboard
    restart: always
    ports:
      - "${WAZUH_DASHBOARD_PORT}:5601"
    environment:
      SERVER_HOST: "0.0.0.0"
      OPENSEARCH_HOSTS: '["https://wazuh-indexer:9200"]'
      WAZUH_MANAGER_HOST: "wazuh-manager"
      TZ: ${TZ} # Inherited from .env
      OPENSEARCH_SSL_VERIFY: "false"
      OPENSEARCH_REQUEST_TIMEOUT: "90000"
      WAZUH_MANAGER_SSL_VERIFY: "false"
      WAZUH_MANAGER_TIMEOUT: "90000"
    volumes:
      - wazuh_dashboard_data:/usr/share/wazuh-dashboard/data # Changed to named volume
    networks:
      - wazuh_network

networks:
  security_network:
    external: true
  wazuh_network:
    external: true
