# Traefik Dynamic Configuration - Middlewares
# Authentication and security middlewares

http:
  middlewares:
    # Authentik Forward Auth Middleware
    authentik:
      forwardAuth:
        address: "http://authentik-server:9000/outpost.goauthentik.io/auth/traefik"
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version

    # OAuth2 Proxy Middleware
    oauth2-auth:
      forwardAuth:
        address: "http://oauth2-proxy:4180/oauth2/auth"
        trustForwardHeader: true
        authResponseHeaders:
          - X-Auth-Request-User
          - X-Auth-Request-Email
          - X-Auth-Request-Access-Token

    # Basic Auth Middleware
    basic-auth:
      basicAuth:
        users:
          - "alwazw:$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi"
          - "manus:$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi"

    # Security Headers Middleware
    security-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - DELETE
        accessControlAllowOriginList:
          - "https://visionvation.com"
          - "https://*.visionvation.com"
          - "https://wazzan.us"
          - "https://*.wazzan.us"
        accessControlMaxAge: 100
        addVaryHeader: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        frameDeny: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
        customRequestHeaders:
          X-Forwarded-Proto: "https"

    # Rate Limiting Middleware
    rate-limit:
      rateLimit:
        average: 100
        period: 1m
        burst: 50

    # IP Whitelist Middleware (for admin services)
    admin-whitelist:
      ipWhiteList:
        sourceRange:
          - "127.0.0.1/32"
          - "10.0.0.0/8"
          - "172.16.0.0/12"
          - "192.168.0.0/16"

    # Compress Middleware
    compress:
      compress: {}

    # Redirect Scheme Middleware
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

    # Strip Prefix Middleware
    strip-prefix:
      stripPrefix:
        prefixes:
          - "/api/v1"

    # Add Prefix Middleware
    add-prefix:
      addPrefix:
        prefix: "/api"

    # Retry Middleware
    retry:
      retry:
        attempts: 3

    # Circuit Breaker Middleware
    circuit-breaker:
      circuitBreaker:
        expression: "NetworkErrorRatio() > 0.30"

    # Custom Headers for Nextcloud
    nextcloud-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Host: "nextcloud.visionvation.com"
        customResponseHeaders:
          X-Frame-Options: "SAMEORIGIN"
          X-Content-Type-Options: "nosniff"
          X-XSS-Protection: "1; mode=block"
          Referrer-Policy: "strict-origin-when-cross-origin"

    # Custom Headers for Grafana
    grafana-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Host: "grafana.visionvation.com"

    # Custom Headers for Authentik
    authentik-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Host: "visionvation.com"
          X-Forwarded-For: ""

    # CORS Middleware
    cors:
      headers:
        accessControlAllowCredentials: true
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
          - "X-Requested-With"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowOriginList:
          - "https://visionvation.com"
          - "https://*.visionvation.com"
          - "https://wazzan.us"
          - "https://*.wazzan.us"
        accessControlMaxAge: 86400
        addVaryHeader: true

  # TLS Options
  tls:
    options:
      default:
        sslProtocols:
          - "TLSv1.2"
          - "TLSv1.3"
        cipherSuites:
          - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
          - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
          - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
          - "TLS_RSA_WITH_AES_256_GCM_SHA384"
          - "TLS_RSA_WITH_AES_128_GCM_SHA256"
        minVersion: "VersionTLS12"
        maxVersion: "VersionTLS13"

